services:
  the-forest-dedicated-server:
    container_name: the-forest-dedicated-server
    image: the-forest-dedicated-server:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8766:8766/udp
      - 27015:27015/udp
      - 27016:27016/udp
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TIMEZONE: ${TZ}
      SERVER_SETTINGS_MODE: ${SERVER_SETTINGS_MODE}
      ALWAYS_UPDATE_ON_START: ${ALWAYS_UPDATE_ON_START}
      SERVER_STEAM_ACCOUNT_TOKEN: ${SERVER_STEAM_ACCOUNT_TOKEN}
      SERVER_NAME: ${SERVER_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SERVER_PASSWORD: ${SERVER_PASSWORD}
    volumes:
      - ./game:/theforest
